//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_leave_availability
    {
        public string emp_id { get; set; }
        public Nullable<int> halfday { get; set; }
        public Nullable<int> short_day { get; set; }
        public Nullable<int> sick_leave { get; set; }
        public Nullable<int> maternity_leave { get; set; }
        public Nullable<int> study_leave { get; set; }
        public Nullable<double> work_years { get; set; }
        public Nullable<int> casual_leave { get; set; }
    }
}
