//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_log
    {
        public string log_id { get; set; }
        public string emp_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string status { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
