//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.emp_log = new HashSet<emp_log>();
            this.leaves = new HashSet<leaves>();
        }
    
        public string emp_id { get; set; }
        public string name { get; set; }
        public string tel_no { get; set; }
        public string email { get; set; }
        public string department { get; set; }
        public string post { get; set; }
        public string manager { get; set; }
        public string gender { get; set; }
        public System.DateTime joined_date { get; set; }
        public string email_password { get; set; }
    
        public virtual ICollection<emp_log> emp_log { get; set; }
        public virtual ICollection<leaves> leaves { get; set; }
    }
}
