//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaves
    {
        public string leave_id { get; set; }
        public string emp_id { get; set; }
        public string type { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<int> duration { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
        public string authorized_by { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
