//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leave_managementEntities : DbContext
    {
        public leave_managementEntities()
            : base("name=leave_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<emp_log> emp_log { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<leaves> leaves1 { get; set; }
        public virtual DbSet<emp_leave_availability> emp_leave_availability { get; set; }
        public virtual DbSet<leave_types> leave_types { get; set; }
    }
}
